spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri:  ${MONGO_ACTIVITY_URI}

  rabbitmq:
    spring:
      rabbitmq:
        addresses: ${SPRING_RABBITMQ_ADDRESSES}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking