spring:
  application:
    name: activityservice

  cloud:
    config:
      enabled: false   # ✅ ADD THIS

  data:
    mongodb:
      uri: ${MONGO_ACTIVITY_URI}

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

server:
  port: 8082

eureka:
  client:
    enabled: false

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking