spring:
  application:
    name: aiservice
    config:
      import:
        optional:configserver:

  datasource:
    url: ${SPRING_DATASOURCE_AI_URL}
    username: ${SPRING_DATASOURCE_AI_USERNAME}
    password: ${SPRING_DATASOURCE_AI_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES}
    listener:
      simple:
        message-converter:
          trusted-packages: "*"


eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true

server:
  port: 8083

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
    key: ${GEMINI_API_KEY}