spring:
  application:
    name: aiservice

  config:
    import: "optional:none"

  datasource:
    url: ${SPRING_DATASOURCE_AI_URL}
    username: ${SPRING_DATASOURCE_AI_USERNAME}
    password: ${SPRING_DATASOURCE_AI_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  cloud:
    config:
      enabled: false

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES}
    listener:
      simple:
        trusted-packages: "*"

eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true

server:
  port: ${PORT:8083}

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: ${GEMINI_API_KEY}

logging:
  level:
    root: INFO
    com.fitness: DEBUG
    com.zaxxer.hikari: DEBUG