spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak-deploy-st9e.onrender.com/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      enabled: false  # ✅ Disables Eureka-style lookup for direct URLs

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
        - TokenRelay= # ✅ Automatically passes the JWT to ALL services below
      httpclient:
        connect-timeout: 10000
        response-timeout: 60s

      routes:
        - id: userservice
          uri: https://userservice-n20l.onrender.com
          predicates:
            - Path=/api/users/**

        - id: activityservice
          uri: https://activityservice-pcce.onrender.com
          predicates:
            - Path=/api/activities/**
          filters:
            - StripPrefix=1

        - id: aiservice
          uri: https://aiservice-z1dw.onrender.com
          predicates:
            - Path=/api/recommendations/**

server:
  port: 8080

eureka:
  client:
    enabled: false